project:
  type: website
  output-dir: docs

website:
  title: "S. C. Fu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: interests.qmd
        text: Interests
      - href: publications.qmd
        text: Publications
      - href: slides.qmd
        text: Slides
      - href: rtutorials.qmd
        text: R Tutorials

format:
  html:
    theme: spacelab
    


