project:
  type: website
  output-dir: docs

website:
  title: "Shih Ching Fu"
  search: false
  page-footer:
    center:
      - icon: github
        text: Github
        href: https://github.com/shihchingfu
      - icon: twitter
        text: Twitter
        href: https://twitter.com/shihchingfu
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/shihchingfu
      - icon: envelope
        text: Email 
        href: mailto:shihching.fu@gmail.com
  navbar:
    title: false
    left:
      - href: index.qmd
      - href: interests.qmd
        text: Interests
      - href: publications.qmd
        text: Publications
      - href: slides.qmd
        text: Slides
      - href: rtutorials.qmd
        text: R Tutorials

format:
  html:
    theme: spacelab
    


