project:
  type: website
  output-dir: docs

website:
  title: "Shih Ching Fu"
  search: false
  page-footer:
    center:
      - text: Github
        href: https://github.com/shihchingfu
      - text: Twitter
        href: https://twitter.com/shihchingfu
      - text: LinkedIn
        href: https://www.linkedin.com/in/shihchingfu
      - text: Email 
        href: mailto:shihching.fu@gmail.com
  navbar:
    title: false
    left:
      - href: index.qmd
      - href: interests.qmd
        text: Interests
      - href: publications.qmd
        text: Publications
      - href: slides.qmd
        text: Slides
      - href: tutorials.qmd
        text: Tutorials

format:
  html:
    theme: simplex
    


