---
title: "Selected Publications^[[Why I’ve removed journal titles from the papers on my CV](https://doi.org/10.1038/d41586-024-02596-y)]"
---

ORCiD: [0000-0002-9077-6026](https://orcid.org/0000-0002-9077-6026)

### 2025

- Wing, C., Hart N. H., **Fu, S. C.**, Nosaka K., Ma’ayah F. (2025). The Use of K-Means Clustering for the Organisation of Training Groups in Australian Football. <https://doi.org/10.1177/17479541251333925>

- Dage, K. C., E. Tremou, B. C. Otahola, E. W. Koch, K. Oh, R. M. Plotkin, V. L. Tang, M. R. Aldhalemi, Z. Bustani, M. I. Fawaz, ..., **Fu, S. C.**, et al. (2025). Detecting the Black Hole Candidate Population in M51’s Young Massive Star Clusters: Constraints on Accreting Intermediate-mass Black Holes. <https://doi.org/10.3847/1538-4357/ad9d37>

### 2024

- Wallace, R., Sambell, R. **Fu, S. C.**, Lo, J., Cook, E. J., Devine A. (2024). Enhancing Nutrition Information Utilisation, Confidence, and Role Legitimacy and Adequacy among Early Childhood Education Professionals through Evidence-Based Online Training. <https://doi.org/10.1177/18369391241270539>

### 2023

- Wilkie, J., Carville, K., **Fu, S. C.**, Kerr, R., Finlayson, K., Tuffrey, T., Lenzo, J. C., Geelhoed, G. (2023). Determining the Actual Cost of Wound Care in Australia. <https://doi.org/10.33235/wpr.31.1.7-18>

- Kutzer, Y., Whitehead, L., Quigley, E., **Fu, S. C.**, Stanley, M. (2023). Subjective versus Objective Sleep Outcomes in Older Adults with and without Uncoupled Sleep Following Online Cognitive Behavioural Therapy for Insomnia. <https://doi.org/10.1111/psyg.12931>

### 2022

- Rees, J., **Fu, S. C.**, Lo, J., Sambell, R., Lewis J. R., Christophersen, C. T., Byrne, M. F., Newton, R. U., Boyle, S., Devine, A. (2022). How a 7-Week Food Literacy Cooking Program Affects Cooking Confidence and Mental Health: Findings of a Quasi-Experimental Controlled Intervention Trial. <https://doi.org/10.3389/fnut.2022.802940>

- Maisey, G., Cattani, M., Devine, A., Lo, J., **Fu, S. C.**, Dunican, I. C. (2022). Digging for data: How sleep is losing out to roster design, sleep disorders, and lifestyle factors. <https://doi.org/10.1016/j.apergo.2021.103617>

### 2021

- Reyes, A., Bartlett D. M., Rankin, T. J., Zaenker, P., Turner, K., Teo, W-P., **Fu, S. C.**, et al. (2021). Clinical Determinants of Dual Tasking in People With Premanifest Huntington Disease. <https://doi.org/10.1093/ptj/pzab016>

### 2020

- Baddeley, A., Brown, W., Milne, R. K., Nair, G., Rakshit, S., Lawrence, T., Phatak, A., **Fu, S. C.** (2020). Optimal thresholding of predictors in mineral prospectivity analysis. <https://doi.org/10.1007/s11053-020-09769-2>

### 2019

- Trott, C. M., **Fu, S. C.**, Murray, S. G., Jordan, C. H., Line, J. L. B., Barry, N., et al. (2019). Robust statistics towards detection of the 21 cm signal from the Epoch of Reionization. <https://doi.org/10.1093/mnras/stz1207>

### Earlier

- Holden, E. J., **Fu, S. C.**, Kovesi, P., Dentith, M., Bourne, B., Hope, M. (2011). Automatic identification of responses from porphyry intrusive systems within magnetic data using image analysis. <https://doi.org/10.1016/j.jappgeo.2011.06.016>

- **Fu, S. C.**, Kovesi, P. (2010). Robust extraction of optic flow differentials for surface reconstruction. <https://doi.org/10.1109/DICTA.2010.85>

- Holden, E. J., Kovesi, P., Dentith, M. C., Wedge, D., Wong, J. C., **Fu, S. C.** (2010). Detection of regions of structural complexity within aeromagnetic data using image analysis. <https://doi.org/10.1109/IVCNZ.2010.6148856>

- **Fu, S. C.**, Milne, G. (2004). A Flexible Automata Model for Disease Simulation. <https://doi.org/10.1007/978-3-540-30479-1_66>

> "Don’t forget that statisticians are the free-est of all scientists - they can work on anything."<br>
> -- David R. Brillinger

